server:
  port: 9091

user:
  username: xiaobai
  age: 20

stu:
  id: 222
  name: xiaohei
  age: 10
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu?serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 000


